/*********************QUIZ********************/



DELIMITER $$

CREATE PROCEDURE SP_AUDITORIA (

IN P_MENSAJE VARCHAR(100)
)

BEGIN
    INSERT INTO LOGS (MENSAJE)
    VALUES (P_MENSAJE);
END $$

DELIMITER ;

CREATE EVENT AUDITORIA
ON SCHEDULE EVERY 1 MINUTE
DO 
	CALL SP_AUDITORIA ('EJECUTADO DESDE AUDITORIA')